{
   "no_index" : {
      "directory" : [
         "t",
         "inc"
      ]
   },
   "meta-spec" : {
      "version" : 1.4,
      "url" : "http://module-build.sourceforge.net/META-spec-v1.4.html"
   },
   "generated_by" : "ExtUtils::MakeMaker version 6.54",
   "distribution_type" : "module",
   "version" : "1.0",
   "name" : "AnyEvent-SNMP",
   "author" : [],
   "license" : "unknown",
   "build_requires" : {
      "ExtUtils::MakeMaker" : 0
   },
   "requires" : {
      "AnyEvent" : 5.23,
      "Net::SNMP" : "5"
   },
   "abstract" : null,
   "configure_requires" : {
      "ExtUtils::MakeMaker" : 0
   }
}
